services:
  postgres:
    image: postgres:14
    container_name: govify_postgres
    environment:
      POSTGRES_DB: govifydb               # Matches DB_NAME from .env
      POSTGRES_USER: admin                # Matches DB_USER from .env
      POSTGRES_PASSWORD: password         # Matches DB_PASS from .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - govify-network

  backend:
    build: ./backend
    container_name: govify_backend
    environment:
      DB_NAME: govifydb                   # Matches DB_NAME from .env
      DB_USER: admin                      # Matches DB_USER from .env
      DB_PASS: password                   # Matches DB_PASS from .env
      DB_HOST: postgres                   # Should remain as 'postgres'
      JWT_SECRET: your_jwt_secret_key     # Matches JWT_SECRET from .env
      PORT: 5000                          # Matches PORT from .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - govify-network
    command: yarn dev

  frontend:
    build: ./frontend
    container_name: govify_frontend
    ports:
      - "3000:3000"
    networks:
      - govify-network
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000

networks:
  govify-network:
    driver: bridge

volumes:
  postgres_data: