services:
  postgres:
    image: postgres:14
    container_name: govify_postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - govify-network

  backend:
    build: ./backend
    container_name: govify_backend
    environment:
      DB_NAME: your_database_name
      DB_USER: your_database_user
      DB_PASS: your_database_password
      DB_HOST: postgres
      JWT_SECRET: your_jwt_secret_key
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - govify-network
    command: yarn dev

  frontend:
    build: ./frontend
    container_name: govify_frontend
    ports:
      - "3000:3000"
    networks:
      - govify-network
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000

networks:
  govify-network:
    driver: bridge

volumes:
  postgres_data: